//
//  Composer.swift
//  PracticeLogger
//
//  Created by Michael Brandt on 5/17/24.
//

import ApolloGQL
import Foundation

struct Composer: Identifiable, Codable {
    var name: String
    var id: ApolloGQL.BigInt?

    enum CodingKeys: String, CodingKey {
        case name
        case id
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        name = try container.decode(String.self, forKey: .name)
        id = try container.decodeIfPresent(ApolloGQL.BigInt.self, forKey: .id)
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(id, forKey: .id)
    }
}

let staticComposers = [
    "Ludwing van Beethoven",
    "Schubert",
    "Johann Sebastian Bach",
    "Bach",
    "Wolfgang Amadeus Mozart",
    "Mozart",
    "Richard Wagner",
    "Wagner",
    "Giovanni Pierluigi da Palestrina",
    "Palestrina",
    "Franz Schubert",
    "Schubert",
    "Josquin des Prez",
    "Brahms",
    "Johannes Brahms",
    "Claude Debussy",
    "Debussy",
    "Franz Josef Haydn",
    "Haydn",
    "Georg Frederic Handel",
    "Handel",
    "Giullame de Machaut",
    "Machaut",
    "Claudio Monteverdi",
    "Monteverdi",
    "Gustav Mahler",
    "Mahler",
    "Igor Stravinsky",
    "Stravinsky",
    "Robert Schumann",
    "Schumann",
    "Pytor Il'yich Tchaikovsky",
    "Tchaikovsky",
    "Fryderyk Chopin",
    "Chopin",
    "Jean Sibelius",
    "Sibelius",
    "Guillaume Dufay",
    "Dufay",
    "Antonin Dvorak",
    "Dvorak",
    "Dmitri Shostakovich",
    "Shoshtakovich",
    "Giuseppe Verdi",
    "Verdi",
    "William Byrd",
    "Franz Liszt",
    "Liszt",
    "Hector Berlioz",
    "Berlioz",
    "Bela Bartok",
    "Bartok",
    "Jean-Philippe Rameau",
    "Maurice Ravel",
    "Ravel",
    "Anton Bruckner",
    "Bruckner",
    "Sergey Prokofiev",
    "Prokofiev",
    "Arnold Schoenberg",
    "Schoenberg",
    "Felix Mendelssohn",
    "Mendelssohn",
    "Richard Strauss",
    "Strauss",
    "Christoph Willibald Gluck",
    "Orlando de Lassus",
    "Henry Purcell",
    "Purcell",
    "Tomas Luis de Victoria",
    "Modest Mussorgsky",
    "Mussorgsky",
    "Johannes Ockeghem",
    "Olivier Messiaen",
    "Gyorgy Ligeti",
    "Sergey Rachmaninov",
    "Rachmaninov",
    "Rachmaninoff",
    "Camille Saint-Saens",
    "Saint-Saens",
    "Karlheinz Stockhausen",
    "Anton Webern",
    "Carl Maria Von Weber",
    "Weber",
    "Antonin Vivaldi",
    "Vivaldi",
    "Alban Berg",
    "Berg",
    "Thomas Tallis",
    "Bedrich Smetana",
    "Smetana",
    "Paul Hindemith",
    "Georg Philipp Telemann",
    "Giacomo Puccini",
    "Pucini",
    "Arcangelo Corelli",
    "Giovanni Gabrieli",
    "Gioachino Rossini",
    "Rossini",
    "Gabriel Faure",
    "Faure",
    "Edvard Grieg",
    "Grieg",
    "Leos Janacek",
    "Janacek",
    "Carl Nielsen",
    "Edward Elgar",
    "Elgar",
    "Heinrich Schutz",
    "Alexander Scriabin",
    "Scriabin",
    "Pierre Boulez",
    "Boulez",
    "Benjamin Britten",
    "Britten",
    "Francois Couperin",
    "Georges Bizet",
    "Bizet",
    "Charles Ives",
    "Ives",
    "Erik Satie",
    "Satie",
    "Gaetano Donizetti",
    "Cesar Franck",
    "Franck",
    "Ralph Vaughan-Williams",
    "Alexander Taneyev",
    "Alfred Schntitke",
    "John Cage",
    "Cage",
    "Dietrich Buxtehude",
    "Vincenzo Bellini",
    "Kristoff Penderecki",
    "Jacob Obrecht",
    "Obrecht",
    "Rimsky-Korsakov",
    "Korsakov",
    "Nikolai Rimsky-Korsakov",
    "Carl Philipp Emanuel Bach",
    "Mikhail Glinka",
    "Glinka",
    "Edgar Varese",
    "Luigi Boccherini",
    "Orlando Gibbons",
    "Jan Pieterszoon Sweelinck",
    "Sweelinck",
    "Philip Glass",
    "Glass",
    "Carlo Gesualdo",
    "Charles Gounod",
    "Samuel Barber",
    "Barber",
    "Domenico Scarlatti",
    "Scarlatti",
    "Aaron Copland",
    "Copland",
    "Alexander Borodin",
    "Borodin",
    "Giacomo Meyerbeer",
    "Isaac Albeniz",
    "Albeniz",
    "Marc-Antoine Charpentier",
    "Manuel de Falla",
    "Steve Reich",
    "Perotin/Leonin"
]
