CREATE TYPE catalogue_type AS ENUM (
    'op',      
    'k',       
    'twv',     
    'bwv',     
    'd',       
    'hob',     
    'rv',      
    's',       
    'hwv',     
    'h',       
    'cnw',     
    'woo',     
    'do',      
    'fp',      
    'cd',      
    'wab',     
    'cff',     
    'ms',      
    'm',       
    'bv',      
    'b',       
    'sz',      
    'jb',      
    'lwv',     
    'eg',      
    'th',      
    'wwv',     
    'wd',      
    'wq',      
    'jw',      
    'trv',
    'mwv'  
);

ALTER TABLE pieces
ADD COLUMN catalogue_type catalogue_type,
ADD COLUMN catalogue_number INT;
