CREATE EXTENSION IF NOT EXISTS moddatetime;

ALTER TABLE pieces
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER handle_updated_at
BEFORE UPDATE ON pieces
FOR EACH ROW
EXECUTE PROCEDURE moddatetime(updated_at);