// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public enum KeySignatureType: String, EnumType {
  case c = "c"
  case csharp = "csharp"
  case cflat = "cflat"
  case d = "d"
  case dsharp = "dsharp"
  case dflat = "dflat"
  case e = "e"
  case esharp = "esharp"
  case eflat = "eflat"
  case f = "f"
  case fsharp = "fsharp"
  case fflat = "fflat"
  case g = "g"
  case gsharp = "gsharp"
  case gflat = "gflat"
  case a = "a"
  case asharp = "asharp"
  case aflat = "aflat"
  case b = "b"
  case bsharp = "bsharp"
  case bflat = "bflat"
  case cminor = "cminor"
  case csharpminor = "csharpminor"
  case cflatminor = "cflatminor"
  case dminor = "dminor"
  case dsharpminor = "dsharpminor"
  case dflatminor = "dflatminor"
  case eminor = "eminor"
  case esharpminor = "esharpminor"
  case eflatminor = "eflatminor"
  case fminor = "fminor"
  case fsharpminor = "fsharpminor"
  case fflatminor = "fflatminor"
  case gminor = "gminor"
  case gsharpminor = "gsharpminor"
  case gflatminor = "gflatminor"
  case aminor = "aminor"
  case asharpminor = "asharpminor"
  case aflatminor = "aflatminor"
  case bminor = "bminor"
  case bsharpminor = "bsharpminor"
  case bflatminor = "bflatminor"
}
