// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public enum PieceFormat: String, EnumType {
  case bagatelle = "bagatelle"
  case ballade = "ballade"
  case canon = "canon"
  case caprice = "caprice"
  case chorale = "chorale"
  case concerto = "concerto"
  case dance = "dance"
  case etude = "etude"
  case fantasy = "fantasy"
  case fugue = "fugue"
  case gavotte = "gavotte"
  case gigue = "gigue"
  case impromptu = "impromptu"
  case intermezzo = "intermezzo"
  case lied = "lied"
  case march = "march"
  case mazurka = "mazurka"
  case mass = "mass"
  case minuet = "minuet"
  case nocturne = "nocturne"
  case overture = "overture"
  case opera = "opera"
  case oratorio = "oratorio"
  case pastiche = "pastiche"
  case prelude = "prelude"
  case polonaise = "polonaise"
  case rhapsody = "rhapsody"
  case requiem = "requiem"
  case rondo = "rondo"
  case sarabande = "sarabande"
  case scherzo = "scherzo"
  case seranade = "seranade"
  case sonata = "sonata"
  case stringQuartet = "string_quartet"
  case suite = "suite"
  case symphony = "symphony"
  case tarantella = "tarantella"
  case toccata = "toccata"
  case variations = "variations"
  case waltz = "waltz"
}
